export type Carro={
    modelo:string,
    marca:string,
    ano:number
}
export const carros:Carro[]=[
    {
        modelo:"chevete",
        ano:1990,
        marca:"tradicional"
    },
    {
        modelo:"fiat",
        ano:1980,
        marca:"tradicional"
    },
    {
        modelo:"gol",
        ano:1970,
        marca:"tradicional"
    },
    {
        modelo:"ferrare",
        ano:1990,
        marca:"importado"
    },
    {
        modelo:"sport",
        ano:1990,
        marca:"importado"
    },
]